### ISSUE TITLE
Links don't work in non-CSS environments

### ISSUE THREAD

**Issue by jonot-cyber** [LeoDog896/webpage#12] opened 2023-05-18 00:22 UTC
<details>

<summary>Old Description (GNU Emacs?)</summary>

Steps to reproduce:
- open GNU Emacs
- open eww `M-x eww`
- type in **https://leodog896.com**

Upon doing so you will see the following:
![image](https://github.com/LeoDog896/webpage/assets/48457507/e62976ea-4873-4161-9228-bea5443b6879)
None of the links to articles work, so the site is pretty hard to use.

</details>

Despite there being accessibility elements, thanks to how the `:after` and `:before` psuedoelements are used to render the styling for the links, readability extensions such as [Firefox's Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages) break when given this page.

**Comment by tristan-f-r** [comment] 2023-05-18 10:49
Thanks! This seems more like an accessibility issue with the way I handled the hover effects - if I can't reproduce this on a screen reader, I'll probably end up closing this.

**Comment by tristan-f-r** [comment] 2023-05-18 12:21
It is! I'll see if I can fix this.

**Comment by tristan-f-r** [comment] 2023-05-18 12:33
Actually, it seems to only be an issue on these types of web renderers that don't use CSS. I realized I implemented an `aria-label` system for accessibility, since using `::before` and `::after` like this demands accessibility reimplementations. Until you can show that this has a demanded case in a browser that _decently_ is used and supports web standards, do let me know.

**Comment by jonot-cyber** [comment] 2023-05-18 13:27
I think that a better question is what do you get from not? Doing it in a strange way breaks support for Emacs, Lynx, Links, many older browsers. It also means that the website will not work on sites like _Reader Mode_, since that would strip out the CSS.

I would understand if supporting these browsers required a large amount of work, or sacrificed functionality for people on modern browsers, but it doesn't. You just have to change one line to this:
```html
<a {href} class={`link-${type}`} title={name + ' >>>'}>{name} <span aria-hidden="true">&gt;&gt;&gt;</span></a>
```
And it works the exact same way, and also supports all of the things I listed.

**Comment by tristan-f-r** [comment] 2023-05-18 13:48
That fix didn't work for me in particular - I don't want to investigate this as I'm not particularly interested in this at the time (especially if it's an issue made by a reader that I already know), but if you want to make a PR for it if the fix works for you I don't mind merging it :+1:. (<strike>I'll keep this as not planned for the time being, but</strike> if you make a mergeable PR I'll close this as completed).

**Comment by tristan-f-r** [comment] 2023-05-18 14:21
nevermind, i could just move `:before` back to it. ([commit](https://github.com/LeoDog896/webpage/commit/cd865445470d643a330e494c52930d5358dabcf7))

**Closed as completed by tristan-f-r** 2023-05-18 14:21 UTC
Labels: bug, help wanted
